baseURL: "https://hugo-profile.netlify.app"
languageCode: "en-us"
title: "Allyson Appleton"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"
    
Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true


params:
  title: "Allyson Appleton"
  description: Text about my cool site
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    # disableThemeToggle: true
    # defaultTheme: "light" # dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # color:
  #   textColor:
  #   secondaryTextColor:
  #   backgroundColor:
  #   secondaryBackgroundColor:
  #   primaryColor:
  #   secondaryColor:

  #   darkmode:
  #     textColor:
  #     secondaryTextColor:
  #     backgroundColor:
  #     secondaryBackgroundColor:
  #     primaryColor:
  #     secondaryColor:

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    brandName: "Allyson Appleton" # Brand name for the brand | default is the title variable
    disableSearch: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "Hi, my name is"
    title: "Allyson"
    subtitle: "Welcome to my Portfolio!"
    content: "I am eager to work on my programming skills throughout this semester in LINGUIST 4PL3: Advanced Programming for Linguists."
    image: /images/high.png
    button:
      enable: false
      name: "Resume"
      url: "#"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url:  https://github.com/allysonappleton
      customIcons:
        - icon: /emoji.png
          url: https://media.itsnicethat.com/original_images/giphy-2021-gifs-and-clips-animation-itsnicethat-02.gif

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/pic.png
    content: |-
      I am a fourth year Cognitive Science of Language at McMaster University. Being in this program has allowed me to explore my interests while also being able to develop valuable skills. 
      My interests include language acquisition (L1 and L2), corpus linguistics, as well as linguistic and speech analysis. 
      
      **The potential audience of my portfolio** are fellow McMaster students, such those in [Cognitive Science of Language](https://linguistics.humanities.mcmaster.ca/undergraduate-programs/cognitive-science-of-language/) or [Linguistics](https://linguistics.humanities.mcmaster.ca/undergraduate-programs/linguistics/) program, as well as linguists and language teachers!
      
      **The goal of my portfolio** is to provide resources to linguists who are interested in speech and language analysis, through programs, web-based apps, and functions.
      
      So far, I have created 3 projects that will make text analysis more convenient for linguists: 1. A shiny app that identifies consonant clusters. 2. A swirl course that teaches users about regex. 3. An advanced function that counts the number of morphemes in a word.
      
      In the future, I would like to include programs that will analyze speech and phonetic data from Praat. 


    skills:
      enable: false
      title: "The technologies I've been working with recently:"
      items:
        - "R"
        - "[Praat](https://www.fon.hum.uva.nl/praat/)"

  # Education
  education:
    enable: false
    # title: "Custom Name"
    index: false
    items:
      - title: " Bachelor of Arts in Honours Cognitive Science of Language"
        school:
          name: "McMaster University"
          url: "https://www.mcmaster.ca/"
        date: "2019 - 2023"
        GPA: "N/A"
        content: |-
          Extracurricular Activities
            - Programming Director and Mentor for Be Strong Together 
            - Social Media Director for SciWise
        featuredLink:
          enable: true
          name: "LinkedIn"
          url: "https://www.linkedin.com/in/allysonappleton/"
      - title: "High School Diploma"
        school:
          name: "Cardinal Carter Catholic High School"
        date: "2015 - 2019"
        GPA: "N/A"
        content: |-
          Student in the International Baccalaureate® (IB) program. 
        featuredLink:
          enable: true
          name: "IB Program"
          url: "https://www.ibo.org/"
      

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Consonant Cluster Hunter
        content: This web-based app makes stringr functions and regex available to users (i.e. linguists), which will allow them to analyze various texts by finding consonant clusters placed in different positions in a word. Click on the GitHub icon to view the code!
        image: /images/projects/ConsonantClusterHunter.png
        featured:
          name: Check out the app here!
          link: https://vo38c1-allyson-appleton.shinyapps.io/consonantclusterhunter/
        badges:
          - "R"
          - "Stringr"
          - "Regex"
          - "shinyApp"
        links:
          - icon: fab fa-github
            url: https://github.com/allysonappleton/Final-Portfolio/blob/main/Consonant%20Cluster%20Hunter/Shiny%20App%20Code

      - title: Introductory Lesson on Regular Expressions
        content: A swirl course designed to provide learners with a foundation in using regular expressions in R. This course is intended to complement my Consonant Cluster Hunter app,as it offers users a behind-the-scenes look at the code (regular expressions) used to identify patterns, like consonant clusters.
        image: /images/projects/regex.png
        featured:
          name: Get the code here!
          link: https://django-converter.herokuapp.com
        badges:
          - "R"
          - "Swirl Course"
          - "Regex"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Morpheme Counter
        content: An advanced function that counts the number of morphemes in a word. Now, you can quickly and easily count the number of morphemes in any English word, leading to valuable insights into its underlying structure!
        image: /images/projects/words.png
        featured:
          name: Get the code here!
          link: https://github.com/allysonappleton/Final-Portfolio/blob/main/Morpheme%20Counter/Advanced%20Function%20Code
        badges:
          - "R"
          - "Advanced Function"
          - "Morphemes"
        links:
          - icon: fab fa-github
            url: https://github.com/allysonappleton/Final-Portfolio/blob/main/Morpheme%20Counter/Advanced%20Function%20Code

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, I’ll get back to you! Also, check out my social networks linked below!
    email: allyson.appleton@gmail.com
    btnName: email me!
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/allysonappleton
      linkedin: https://www.linkedin.com/in/allysonappleton/
      twitter: https://twitter.com
      instagram: https://www.instagram.com/allysonappleton/
      facebook: https://www.facebook.com/allyson.appleton.90

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false
